# Site Settings
title: Nicolas Xaviers Thompsons Webpage
tagline: The NXT webpage
email: nxthompson96@gmail.com
description: 
  My own webpage made in github pages
permalink: pretty
favicon: /favicon.svg
hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top

paginate: 3
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: nxthompson
  comments: true


plugins:
  #  - jekyll-sitemap
  - jekyll-paginate
    #  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compact
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Nicholas Xavier Thompson"
      layout: post

markdown: kramdown
highlighter: rouge

remote_theme: chrisrhymes/bulma-clean-theme
